# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d7b376aa84a7d035687621e7dc9c2abc20e3cd89714191c5858be868ef318632ff2bf9d0a377bf5328cee4d0456d7a19951a359fd6c19c08be75cfd789d692c

test:
  secret_key_base: 1133c16aa7ad6f609de2560a56aa591fe011abf1cea85fbc351896c9ba3037243e431513f13f5e301c10b98b3ab6ef8f6702413144083b226777eb1041a02625

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
